default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/alerts_development

test:
  <<: *default
  database: db/alerts_test

production:
  <<: *default
  database: db/alerts_production
